

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=True
      - POSTGRES_USER=fashion_user
      - POSTGRES_PASSWORD=fashion_pass
      - POSTGRES_DB=fashion_db
    networks:
      - default
    volumes:
      - ./static:/app/static   # แชร์ static files
      - ./media:/app/media     # แชร์ media files
      - ./wait-for-it.sh:/app/wait-for-it.sh # เพิ่ม wait-for-it.sh
    command: >
      bash -c "
      ./wait-for-it.sh db:5432 -- python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: fashion_user
      POSTGRES_PASSWORD: fashion_pass
      POSTGRES_DB: fashion_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default

volumes:
  postgres_data:

networks:
  default:
    driver: bridge