version: '3.8'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=True
    networks:
      - default
    volumes:
      - ./static:/app/static   # เพิ่มบรรทัดนี้
      - ./media:/app/media
    command: >
      bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: fashion_user
      POSTGRES_PASSWORD: fashion_pass
      POSTGRES_DB: fashion_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default

volumes:
  postgres_data:

networks:
  default:
    driver: bridge