# Generated by Django 5.2 on 2025-04-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rental", "0002_product_trend"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
        migrations.AddField(
            model_name="product",
            name="image_url",
            field=models.URLField(default="https://example.com/default_image.jpg"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
