# Generated by Django 5.2 on 2025-04-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rental", "0003_remove_product_image_product_image_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
    ]
